CREATE TABLE IF NOT EXISTS "eeshop_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eeshop_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eeshop_subcategory" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eeshop_subcategory_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"category_id" integer NOT NULL
);
--> statement-breakpoint
DROP TABLE "eeshop_post";--> statement-breakpoint
ALTER TABLE "eeshop_product" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ALTER COLUMN "price" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ALTER COLUMN "description" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ADD COLUMN "images" varchar(1024)[] DEFAULT '{}'::varchar[] NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ADD COLUMN "subcategory_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ADD COLUMN "tags" varchar(256)[] DEFAULT '{}'::varchar[] NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ADD COLUMN "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_product" ADD COLUMN "updated_at" timestamp with time zone;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "eeshop_subcategory" ADD CONSTRAINT "eeshop_subcategory_category_id_eeshop_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."eeshop_category"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "eeshop_product" ADD CONSTRAINT "eeshop_product_subcategory_id_eeshop_subcategory_id_fk" FOREIGN KEY ("subcategory_id") REFERENCES "public"."eeshop_subcategory"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "eeshop_product" USING btree ("name");