CREATE TABLE IF NOT EXISTS "eeshop_product_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eeshop_product_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"url" text NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eeshop_product_tags" (
	"product_id" integer NOT NULL,
	"tag_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "eeshop_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "eeshop_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(64) NOT NULL,
	CONSTRAINT "eeshop_tag_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "eeshop_category" ADD COLUMN "description" text NOT NULL;--> statement-breakpoint
ALTER TABLE "eeshop_category" ADD COLUMN "image_url" text;--> statement-breakpoint
ALTER TABLE "eeshop_subcategory" ADD COLUMN "description" text NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "eeshop_product_images" ADD CONSTRAINT "eeshop_product_images_product_id_eeshop_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."eeshop_product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "eeshop_product_tags" ADD CONSTRAINT "eeshop_product_tags_product_id_eeshop_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."eeshop_product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "eeshop_product_tags" ADD CONSTRAINT "eeshop_product_tags_tag_id_eeshop_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."eeshop_tag"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
ALTER TABLE "eeshop_product" DROP COLUMN IF EXISTS "images";--> statement-breakpoint
ALTER TABLE "eeshop_product" DROP COLUMN IF EXISTS "tags";--> statement-breakpoint
ALTER TABLE "eeshop_category" ADD CONSTRAINT "eeshop_category_name_unique" UNIQUE("name");--> statement-breakpoint
ALTER TABLE "eeshop_subcategory" ADD CONSTRAINT "eeshop_subcategory_name_unique" UNIQUE("name");